package hzpro.com.tradingdesk.arbitrage.model;

public enum OpportunityCloseReason {
    SPREAD_BELOW_THRESHOLD,
    PRICE_DATA_STALE,
    PRICE_DATA_UNAVAILABLE,
    ORDER_CREATION_FAILED,
    ORDERBOOK_PRICE_BELOW_THRESHOLD,
    ORDER_BOOK_NOT_ENOUGH_AMOUT,
    ORDERBOOK_EMPTY,
    MINIMIM_ORDER_COST_NOT_MET,
    ACTIVE_PAIR_LIMIT_REACHED,
    ORDERS_CREATED,
    UNKNOWN
}
